class Solution {
    public List<Integer> grayCode(int n) {
        // Initialize an empty list to hold the Gray code sequence
        List<Integer> result = new ArrayList<>();
      
        // Calculate the total number of elements in the Gray code sequence, which is 2^n
        int totalNumbers = 1 << n;
      
        // Generate the Gray code sequence
        for (int i = 0; i < totalNumbers; ++i) {
            // The Gray code is generated by XOR-ing the current number 
            // with the number right-shifted by one bit
            int grayCodeNumber = i ^ (i >> 1);
            // Add the generated Gray code number to the result list
            result.add(grayCodeNumber);
        }
      
        // Return the complete list of Gray code sequence
        return result;
    }
}